import numpy as np


def load_ccm_data(path="ccm_data.csv"):
    """
    Load CCM data from CSV (generated by R).
    """
    Accm = []
    Bccm = []
    time_ccm = []
    with open(path, "r") as f:
        next(f)  # Skip header
        for line in f:
            parts = line.strip().split(",")
            Accm.append(float(parts[0]) if parts[0] != "NA" else np.nan)
            Bccm.append(float(parts[1]) if parts[1] != "NA" else np.nan)
            time_ccm.append(float(parts[2]) if parts[2] != "NA" else np.nan)
    return {
        "Accm": np.array(Accm),
        "Bccm": np.array(Bccm),
        "time_ccm": np.array(time_ccm),
    }


def make_ccm_data(
    sp_sd=0.125,
    obs_sd=0.025,
    Sstr=0.375,
    times=10,
    burnin=100,
    number_of_chains=20,
    seednum=2718,
):
    """
    Generate simulated data for CCM analysis.

    Creates coupled logistic maps where A is forced by B, but B is not forced by A.

    Parameters
    ----------
    sp_sd : float
        Standard deviation for process noise (random growth rates)
    obs_sd : float
        Standard deviation for observation error (multiplicative noise)
    Sstr : float
        Forcing strength of process B on process A
    times : int
        Number of sequential observations in each plot
    burnin : int
        Burn-in time to remove initial transients
    number_of_chains : int
        Number of spatially replicated plots
    seednum : int
        Random seed for reproducibility

    Returns
    -------
    dict
        Dictionary with 'Accm', 'Bccm', and 'time_ccm'
    """
    np.random.seed(seednum)

    Accm = []
    Bccm = []
    time_ccm = []

    for i in range(number_of_chains):
        rx = 3.8 + np.random.normal(0, sp_sd)
        ry = 3.6 + np.random.normal(0, sp_sd)

        total_len = times + burnin
        x = np.zeros(total_len)
        y = np.zeros(total_len)

        x[0] = np.random.uniform(0, 1)
        y[0] = np.random.uniform(0, 1)

        for ii in range(1, total_len):
            x[ii] = x[ii - 1] * (rx - rx * x[ii - 1] - Sstr * y[ii - 1])
            y[ii] = y[ii - 1] * (ry - ry * y[ii - 1])

            if x[ii] < 0:
                x[ii] = -x[ii]
            elif x[ii] > 1:
                x[ii] = 1 + (1 - x[ii])

            if y[ii] < 0:
                y[ii] = -y[ii]
            elif y[ii] > 1:
                y[ii] = 1 + (1 - y[ii])

        x = x[burnin:]
        y = y[burnin:]

        x = x * np.random.lognormal(0, obs_sd, len(x))
        y = y * np.random.lognormal(0, obs_sd, len(y))

        Accm.append(np.nan)
        Accm.extend(x.tolist())

        Bccm.append(np.nan)
        Bccm.extend(y.tolist())

        time_ccm.append(np.nan)
        time_ccm.extend(list(range(1, times + 1)))

    return {
        "Accm": np.array(Accm),
        "Bccm": np.array(Bccm),
        "time_ccm": np.array(time_ccm),
    }
